name: Tests unitaires

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du repository
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer pytest
        run: pip install pytest

      - name: Lancer les tests
        run: pytest